### ISSUE TITLE
印钞机会断流，原因未知

### ISSUE THREAD

**Issue by xiaoluofa** [LuminolMC/Luminol#1]

**Comment by MrHua269** [comment]
> _No description provided._

如果是使用的1.20.2版本请更新到最新版并将配置文件中的skip_secondary_poi_if_is_empty改为false

**Comment by xiaoluofa** [comment]
> > _No description provided._
> 
> 如果是使用的1.20.2版本请更新到最新版并将配置文件中的skip_secondary_poi_if_is_empty改为false

回复这么快啊，目前我猜测是和配置文件优化实体那个有关系，我现在已经关闭在测试了，我使用的是修复了实体传送的那个版本

**Comment by xiaoluofa** [comment]
大佬有没有交流群，我可以及时反应一些问题。我服日常50+在线。这个分支确实不错~

**Comment by MrHua269** [comment]
> 大佬有没有交流群，我可以及时反应一些问题。我服日常50+在线。这个分支确实不错~

az,刚加上（手残还给我截图粘README里了），在组织那个简介里()

**Comment by xiaoluofa** [comment]
破案配置文件导致的，请关闭~
