### ISSUE TITLE
在folia 1.20.4 运行到的插件换了 luminol 跑不了

### ISSUE THREAD

**Issue by cgw2023** [LuminolMC/Luminol#10]
把folia-bundler-1.20.4-R0.1-SNAPSHOT-reobf 换成 Luminol MC1.20.4 - 2024-03-16T23:03:24Z 有插件跑不了
例如
Executableitems 
Score
Bluemap residence
Superharvest

报错和伺服器记录在
https://paste.denizenscript.com/View/121199

**Comment by cgw2023** [comment]
我刚刚看了一下有LightingLuminol，用LightingLuminol跑的话就没问题，但我就想知道LightingLuminol比folia多了什么
然后就是LightingLuminol和Luminol的差距是什么导致Luminol跑不了某些插件

**Comment by cgw2023** [comment]
我应该怎样跟那些插件作者说？ 我不懂java

**Comment by Klop233** [comment]
现在做了folia兼容的bukkit插件普遍存在这个问题，都只认folia本身，不认他的fork，直接开issue说服务端类型识别错误就好了

**Comment by Klop233** [comment]
其实直接用lightingluminol就可以了，等他们更新也得挺久

**Comment by MrHua269** [comment]
> 我应该怎样跟那些插件作者说？ 我不懂java

az，来QQ群罢（）

**Comment by Klop233** [comment]
http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=YdDENRoTFrf2gHRHr5qGQYcoXw_w36qw&authKey=S9wKV5oZ22NHhPUEtSdG3tiMzZ%2B8P3oAX0yrxoNZarPDmaTe6gG%2Fcp5LvqQC9DwT&noverify=0&group_code=368632360

**Comment by MrHua269** [comment]
> > 我应该怎样跟那些插件作者说？ 我不懂java
> 
> az，来QQ群罢（）

discord也行，我discord用户名在我的主页有（）
