### ISSUE TITLE
我遇到了一个问题

### ISSUE THREAD

**Issue by Luoboawa** [LuminolMC/Luminol#16]
### 服务端版本 LuminolMC Version

git-Luminol-"c06f539" MC:1.20.4

### 预期的行为 Expected behavior

不报错啊

### 观测到的实际行为 Observed/Actual behavior

报错+崩服

### 复现步骤 Steps/models to reproduce

无规律

### 插件与数据包列表。 Plugin and Datapack List.

Server Plugins (25):
Paper Plugins:
- HuskHomes
Bukkit Plugins:
- BlockLocker, CMILib, CoreProtect, Essentials, FreedomChat, GSit, HeadDrop, LiteSignIn, LuckPerms, MiniMOTD
PlaceholderAPI, PlayerGuild, PlayerMenu, PlayerPoints, PlugManX, ProtocolLib, Residence, TAB, TrChat, Vault
 ViaBackwards, ViaRewind, ViaVersion, WorldEdit

**Comment by MrHua269** [comment]
请提供日志或者报错的内容

**Comment by GLDYM** [comment]
**So where is ur log? If u do not provide log file, the only thing I can do is to ask GOD why u cannot use viaversion.**

---

**所以你的日志哪里去了？不提供日志，我能做的就只有给你算一卦。**

**Comment by 2534905003** [comment]
> 请提供日志或者报错的内容

[ERROR.log](https://github.com/user-attachments/files/15522222/ERROR.log)

**Comment by 2534905003** [comment]
> **So where is ur log? If u do not provide log file, the only thing I can do is to ask GOD why u crashed.**
> 
> **所以你的日志哪里去了？不提供日志，我能做的就只有给你算一卦。**

今天我的脑子找不到了

**Comment by MrHua269** [comment]
Try setting "enabled" of fixes.folia.prevent_teleportasync_call_during_moving to true
