### ISSUE TITLE
NaturalMobSpawning

### ISSUE THREAD

**Issue by PedroMPagani** [LuminolMC/Luminol#17]
### 描述你希望添加的功能。 Describe the feature you'd like.

The natural mob spawning may load chunks that aren't ready for spawning the mobs, causing mspt spikes, if you create something like a patch for this, that would be awesome.

**Comment by MrHua269** [comment]
![image](https://github.com/LuminolMC/Luminol/assets/79621885/e6534f3d-1ea5-4337-9120-4fafb78d9115)
I think Paper has already done this

**Comment by PedroMPagani** [comment]
I am not sure, I believe this happens mostly on the nether search for fortress.
 Can you add me on discord? I'd love to contribute to Luminol, we run
discord.gg/donutsmp.
