### ISSUE TITLE
TNT weird behavier

### ISSUE THREAD

**Issue by MidnightTale** [LuminolMC/Luminol#19]
### 服务端版本 LuminolMC Version

Luminol version 1.20.6-DEV-ver/1.20.6@b208bcc

### 预期的行为 Expected behavior

https://file.hynse.net/public/media/2024-06-15%2022-01-08.mp4

Folia version 1.20.6-DEV-master@36e5e83 work fine TNT  explode more 1 block unlike actual behavior.

### 观测到的实际行为 Observed/Actual behavior

https://file.hynse.net/public/media/2024-06-15%2021-58-34.mp4

TNT is explode early 1 block.

### 复现步骤 Steps/models to reproduce

1. Build tree farm this https://file.hynse.net/public/schematic/612_utf.litematic 
2. Turn on tree farm
3. Place jungle sapling in tree farm dirt block
4. Watch TNT

### 插件与数据包列表。 Plugin and Datapack List.

no plugin only datapack
![image](https://github.com/LuminolMC/Luminol/assets/125941391/16b838c2-94c3-43f2-913b-a19fa8183af4)

### 更多详细信息。 The more information.

both test Folia and Luminol use the same config setting
https://file.hynse.net/public/config/folia/

**Comment by MrHua269** [comment]
Update your server jar to acc31af9f62fc1948dea431f7e1fe4ad542358e2 and set reduce_entity_fluid_lookups_if_no_fluids to false
