### ISSUE TITLE
Plugin compability issue (QuickShop) 

### ISSUE THREAD

**Issue by DarkyG2** [LuminolMC/Luminol#23]
### 服务端版本 LuminolMC Version

This server is running Luminol version git-Luminol-"bbd1c34" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: bbd1c34 on ver/1.20.4) Unknown version Previous version: git-Folia-"ef2c697" (MC: 1.20.4)

### 预期的行为 Expected behavior

Plugin should work with the correct display format

### 观测到的实际行为 Observed/Actual behavior

The virtual format of display of quickshop isn't working. On normal Folia I have 0 issues

### 复现步骤 Steps/models to reproduce

1. use this jar https://www.mediafire.com/file/5alz20i55bnmnx9/QuickShop-Hikari-6.1.0.2.jar/file
2. test with normal folia, 0 errors
3. test with LuminolMC: Errors and not working as intended
4. Error: https://pastebin.com/H0PDAFXv

### 插件与数据包列表。 Plugin and Datapack List.

private

### 更多详细信息。 The more information.

Here is the error: https://pastebin.com/H0PDAFXv

**Comment by MrHua269** [comment]
Try 592877ef28282ec5323c3f1239db4b396a08da0e

**Comment by DarkyG2** [comment]
> Try [592877e](https://github.com/LuminolMC/Luminol/commit/592877ef28282ec5323c3f1239db4b396a08da0e)

Still the same issue: https://pastebin.com/jcGGM8Fv

**Comment by MrHua269** [comment]
Try 5579f65eae6e8ddec4ace59d299bc2cf2dd1acee ()

**Comment by DarkyG2** [comment]
> Try [5579f65](https://github.com/LuminolMC/Luminol/commit/5579f65eae6e8ddec4ace59d299bc2cf2dd1acee) ()

Fixed !
