### ISSUE TITLE
可配置的原版特性配置文件那在哪里？

### ISSUE THREAD

**Issue by woniusheji** [LuminolMC/Luminol#31]
### 描述你希望添加的功能。 Describe the feature you'd like.

可配置的原版特性配置文件那在哪里？

### 其他 Other

可配置的原版特性配置文件那在哪里？

**Comment by WangBen137** [comment]
在根目录下

**Comment by cygbs** [comment]
在服务器根目录下有一个 luminol_config 文件夹，其中包含了一个配置文件，在那里您可以配置原版特性和 Luminol 服务端的所有功能。

There is a luminol_config directory located at the root of the server. Inside this directory, you will find a configuration file where you can customize all the original features and functionalities of the Luminol server.
