### ISSUE TITLE
PlayerRespawnEvent、PlayerPostRespawnEvent无法调用

### ISSUE THREAD

**Issue by yvmouX** [LuminolMC/Luminol#37]
### 服务端版本 LuminolMC Version

Luminol 1.21.1 - 6fb1f69

### 预期的行为 Expected behavior

PlayerRespawnEvent PlayerPostRespawnEvent正常使用

### 观测到的实际行为 Observed/Actual behavior

@EventHandler
    public void onPlayerRespawn(PlayerRespawnEvent event) {
        Bukkit.getConsoleSender().sendMessage("玩家重生了");
        Player player = event.getPlayer();
        player.addPotionEffect(new PotionEffect(PotionEffectType.SLOWNESS, 1200, 2));
    }
    玩家死亡后控制台不会打印任何东西

### 复现步骤 Steps/models to reproduce

（（（

### 插件与数据包列表。 Plugin and Datapack List.

无（除了测试插件）
测试插件源码https://github.com/yvmouX/ArkTools

**Comment by MrHua269** [comment]
在Folia上所述事件已被移除且不会恢复
